// <auto-generated />
using System;
using Education.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Education.Persistence.Migrations
{
    [DbContext(typeof(EducationDbContext))]
    [Migration("20220513200317_EducationMigrationInitial")]
    partial class EducationMigrationInitial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Education.Domain.Course", b =>
                {
                    b.Property<Guid>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(14,2)");

                    b.Property<DateTime?>("PublishDate")
                        .HasColumnType("datetime2");

                    b.HasKey("CourseId");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            CourseId = new Guid("c4561195-0ccd-4bfd-82db-bdb89630a783"),
                            CreationDate = new DateTime(2022, 5, 13, 14, 3, 17, 392, DateTimeKind.Local).AddTicks(9503),
                            Description = "Basic C# Course",
                            Name = "C# course from zero to hero",
                            Price = 80m,
                            PublishDate = new DateTime(2024, 5, 13, 14, 3, 17, 392, DateTimeKind.Local).AddTicks(9510)
                        },
                        new
                        {
                            CourseId = new Guid("0005ea22-3146-45be-84b7-2177190e4b0e"),
                            CreationDate = new DateTime(2022, 5, 13, 14, 3, 17, 392, DateTimeKind.Local).AddTicks(9542),
                            Description = "Java Course",
                            Name = "Advanced Java Course",
                            Price = 100m,
                            PublishDate = new DateTime(2024, 5, 13, 14, 3, 17, 392, DateTimeKind.Local).AddTicks(9543)
                        },
                        new
                        {
                            CourseId = new Guid("a0b2cc9d-a268-452f-b64b-11a6995470ec"),
                            CreationDate = new DateTime(2022, 5, 13, 14, 3, 17, 392, DateTimeKind.Local).AddTicks(9554),
                            Description = "Master in Unit Test with CQRS",
                            Name = "Unit Tests in .NET 6",
                            Price = 150m,
                            PublishDate = new DateTime(2024, 5, 13, 14, 3, 17, 392, DateTimeKind.Local).AddTicks(9554)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
